"""role changed

Revision ID: ee337a0e2bf8
Revises: 4bf042c43d49
Create Date: 2018-02-23 15:40:21.747076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee337a0e2bf8'
down_revision = '4bf042c43d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'desc')
    # ### end Alembic commands ###
